AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template for Realwin.ai core lambda functions

Parameters:
  Stage:
    Type: String
    Description: Stage to deploy resources to
    Default: "dev"
    AllowedValues: [dev, prod]

  BatchJobQueueName:
    Type: String
    Default: realwin_cricket_queue

  BatchJobDefinitionName:
    Type: String
    Default: realwin_cricket_def

  # Optional: include a simple timestamp in JobName to make each run visibly unique
  IncludeTimestampInJobName:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: 'If "true", appends YYYYMMDDHH to the JobName (helpful for log searching).'

Conditions:
  IsProdStack: !Equals [ !Ref "AWS::StackName", "realwin-serverless-prod" ]
  UseTimeSuffix: !Equals [ !Ref IncludeTimestampInJobName, "true" ]

Globals:
  Function:
    Timeout: 900
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:

  SchedulerIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SchedulerBatchSubmit
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - batch:SubmitJob
                Resource:
                  - !Sub arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job-queue/${BatchJobQueueName}
                  - !Sub arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job-definition/${BatchJobDefinitionName}:*

  CricketEvery4HoursScheduler:
    Condition: IsProdStack
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: cricket-every-4-hours
      Description: 'Submit job every 4 hours'
      # Simple "every 4 hours"
      ScheduleExpression: rate(4 hours)
      ScheduleExpressionTimezone: UTC
      State: ENABLED
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: 'arn:aws:scheduler:::aws-sdk:batch:submitJob'
        RoleArn: !GetAtt SchedulerIamRole.Arn
        # Build a dynamic JobName:
        # - Always includes Stage and Region.
        # - Optionally includes a YYYYMMDDHH suffix (controlled by IncludeTimestampInJobName).
        Input: !If
          - UseTimeSuffix
          - !Sub |
              {
                "JobName": "${Stage}-cricket-4h-${AWS::Region}-${AWS::StackName}-YYYYMMDDHH",
                "JobQueue": "${BatchJobQueueName}",
                "JobDefinition": "${BatchJobDefinitionName}",
                "ContainerOverrides": {
                  "Command": ["python","main.py","{}"]
                }
              }
          - !Sub |
              {
                "JobName": "${Stage}-cricket-4h-${AWS::Region}-${AWS::StackName}",
                "JobQueue": "${BatchJobQueueName}",
                "JobDefinition": "${BatchJobDefinitionName}",
                "ContainerOverrides": {
                  "Command": ["python","main.py","{}"]
                }
              }

  # CricketFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: cricket/
  #     Handler: app.lambda_handler
  #     Runtime: python3.12
  #     MemorySize: 512
  #     Role: arn:aws:iam::171171309607:role/realwin-lambda
  #     Architectures: [x86_64]

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
