"""Add missing columns to User

Revision ID: 9da172240263
Revises: 425ac62dbc73
Create Date: 2025-08-31 02:58:39.199248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9da172240263'
down_revision = '425ac62dbc73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_football_predictions_create_date', table_name='football_predictions')
    op.drop_index('ix_football_predictions_date', table_name='football_predictions')
    op.drop_index('ix_football_predictions_id', table_name='football_predictions')
    op.drop_index('ix_football_predictions_key', table_name='football_predictions')
    op.drop_index('ix_football_predictions_update_date', table_name='football_predictions')
    op.drop_table('football_predictions')
    op.drop_index('ix_cricket_predictions_create_date', table_name='cricket_predictions')
    op.drop_index('ix_cricket_predictions_date', table_name='cricket_predictions')
    op.drop_index('ix_cricket_predictions_id', table_name='cricket_predictions')
    op.drop_index('ix_cricket_predictions_key', table_name='cricket_predictions')
    op.drop_index('ix_cricket_predictions_update_date', table_name='cricket_predictions')
    op.drop_table('cricket_predictions')
    op.add_column('User', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('User', sa.Column('sub', sa.String(), nullable=True))
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=True)
    op.drop_column('User', 'role')
    op.add_column('permission', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_permission_name', 'permission', type_='unique')
    op.drop_index('ix_permission_name', table_name='permission')
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.create_index(op.f('ix_permission_create_date'), 'permission', ['create_date'], unique=False)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=True)
    op.create_index(op.f('ix_permission_update_date'), 'permission', ['update_date'], unique=False)
    op.add_column('role', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_role_name', 'role', type_='unique')
    op.drop_index('ix_role_name', table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_index(op.f('ix_role_create_date'), 'role', ['create_date'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    op.create_index(op.f('ix_role_update_date'), 'role', ['update_date'], unique=False)
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_permission_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permission', ['permission_id'], ['id'])
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'User', ['user_id'], ['id'])
    op.add_column('user_settings', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('user_settings', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_settings', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_constraint('uq_user_settings_user_id', 'user_settings', type_='unique')
    op.create_index(op.f('ix_user_settings_create_date'), 'user_settings', ['create_date'], unique=False)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=True)
    op.create_index(op.f('ix_user_settings_update_date'), 'user_settings', ['update_date'], unique=False)
    op.drop_constraint('user_settings_user_id_fkey', 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key('user_settings_user_id_fkey', 'user_settings', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_settings_update_date'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_create_date'), table_name='user_settings')
    op.create_unique_constraint('uq_user_settings_user_id', 'user_settings', ['user_id'])
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('user_settings', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_settings', 'update_date')
    op.drop_column('user_settings', 'create_date')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_role_update_date'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_create_date'), table_name='role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index('ix_role_name', 'role', ['name'], unique=False)
    op.create_unique_constraint('uq_role_name', 'role', ['name'])
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('role', 'update_date')
    op.drop_column('role', 'create_date')
    op.drop_index(op.f('ix_permission_update_date'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_create_date'), table_name='permission')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.create_index('ix_permission_name', 'permission', ['name'], unique=False)
    op.create_unique_constraint('uq_permission_name', 'permission', ['name'])
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('permission', 'update_date')
    op.drop_column('permission', 'create_date')
    op.add_column('User', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('User', 'sub')
    op.drop_column('User', 'phone')
    op.create_table('cricket_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cricket_predictions_pkey'),
    sa.UniqueConstraint('key', name='cricket_predictions_key_unique')
    )
    op.create_index('ix_cricket_predictions_update_date', 'cricket_predictions', ['update_date'], unique=False)
    op.create_index('ix_cricket_predictions_key', 'cricket_predictions', ['key'], unique=False)
    op.create_index('ix_cricket_predictions_id', 'cricket_predictions', ['id'], unique=False)
    op.create_index('ix_cricket_predictions_date', 'cricket_predictions', ['date'], unique=False)
    op.create_index('ix_cricket_predictions_create_date', 'cricket_predictions', ['create_date'], unique=False)
    op.create_table('football_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='football_predictions_pkey'),
    sa.UniqueConstraint('key', name='football_predictions_key_unique')
    )
    op.create_index('ix_football_predictions_update_date', 'football_predictions', ['update_date'], unique=False)
    op.create_index('ix_football_predictions_key', 'football_predictions', ['key'], unique=False)
    op.create_index('ix_football_predictions_id', 'football_predictions', ['id'], unique=False)
    op.create_index('ix_football_predictions_date', 'football_predictions', ['date'], unique=False)
    op.create_index('ix_football_predictions_create_date', 'football_predictions', ['create_date'], unique=False)
    # ### end Alembic commands ###
