"""add trigger_id and delivery fields to sent_messages

Revision ID: f907bf7tm1se
Revises: 66bed4986c18
Create Date: 2025-09-17 20:30:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f907bf7tm1se"
down_revision = "66bed4986c18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add trigger_id field to sent_messages table
    op.execute("""
        ALTER TABLE sent_messages 
        ADD COLUMN IF NOT EXISTS trigger_id VARCHAR(50);
    """)

    # Add delivery tracking fields to sent_messages table
    op.execute("""
        ALTER TABLE sent_messages 
        ADD COLUMN IF NOT EXISTS delivered BOOLEAN DEFAULT FALSE;
    """)

    op.execute("""
        ALTER TABLE sent_messages 
        ADD COLUMN IF NOT EXISTS read_by_user BOOLEAN DEFAULT FALSE;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove added fields from sent_messages table
    op.execute("""
        ALTER TABLE sent_messages 
        DROP COLUMN IF EXISTS trigger_id;
    """)

    op.execute("""
        ALTER TABLE sent_messages 
        DROP COLUMN IF EXISTS delivered;
    """)

    op.execute("""
        ALTER TABLE sent_messages 
        DROP COLUMN IF EXISTS read_by_user;
    """)

    # ### end Alembic commands ###
